version: '3'
services:
  bot:
    image: YourImageName:YourTag
    container_name: Give_me_a_name
    restart: unless-stopped
    environment:

      Prefix: "YOUR_PREFIX" # defaults to "-" if you remove Prefix:
      AllowedChannelName: "YOUR_ALLOWED_TEXT_CHANNELNAME" # Only allows commands in a channel that contains this in the name
                                                     # leave it empty if you dont want this feature, it is case sensitive.
                                                     # eg "music" will make it so the bot will error if a botcommand is posted out of music_room.
      DiscordToken: "YOUR_DISCORD_TOKEN"

      LavaLink_HostName: "YOUR_LAVALINK_HOSTNAME"
      LavaLink_Port:  "YOUR_LAVALINK_PORT"
      LavaLink_Password: "YOUR_LAVALINK_PASSWORD"
      LavaLink_SSL: "Change_me" # set to True if you have added ssl to your lavalink remove if false
