name: Docker Image CI

on:
  push:
    branches: [ "Main" ]

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: login
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with: 
        username: ${{ secrets.DockerU }}
        password: ${{ secrets.DockerP }}
      
    - name: Build the Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        push: true
        tags: nalinhue/donkbot:latest
